GET http://localhost:5000/
###
GET http://127.0.0.1:5000/users?page=1&limit=10
###
POST  http://localhost:5000/insert
###
GET http://localhost:5000/user?page=1&limit=10


###

POST http://127.0.0.1:5000/register HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpYXQiOjE1MTYyMzkwMjJ9.UqHQ1Nu14ou1Q4KIJWrMxr1NKfPPvQqflN-RJzskYfk
# Using Faker now

{
"name":"John",
"email":"j@tttt.com",
"password":"123",
"roles":["basic"],
"role":"basic"
}





###
@email = "leopoldo.price@hotmail.com"
@pass = "123"

###

# @name sendotp
POST http://127.0.0.1:5000/user/sendotp HTTP/1.1
content-type: application/json

{
"email":{{email}},
"password":{{pass}}
}

###
@authOTP = {{sendotp.response.body.$.otp}}

###
POST http://127.0.0.1:5000/user/login_with_otp HTTP/1.1
content-type: application/json

{
"email":{{email}},
"otp":"{{authOTP}}"
}

###
# @name login
POST http://127.0.0.1:5000/user/login HTTP/1.1
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwicGFzc3dvcmQiOiIxMjM0NTYiLCJpYXQiOjE1MTYyMzkwMjJ9.UqHQ1Nu14ou1Q4KIJWrMxr1NKfPPvQqflN-RJzskYfk

{
"email":{{email}},
"password":{{pass}}
}

###

@id = {{login.response.body.$.id}}
@authToken = {{login.response.headers.X-AuthToken}}

POST http://127.0.0.1:5000/admin_home HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
"id":10,
"userName":"ts1",
"password":"ts1",
"role": "admin"
}


###

POST http://127.0.0.1:5000/secured_api HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
"id":10,
"userName":"ts1",
"password":"ts1",
"role": "basic"

}


###
POST http://127.0.0.1:5000/public_api HTTP/1.1
content-type: application/json
Authorization: Bearer {{authToken}}

{
"id":10,
"userName":"ts1",
"password":"ts1"
}
###

GET http://127.0.0.1:5000/getTest 
###

POST http://localhost:5000/upload/

### Book API

GET http://localhost:5000/books

###
GET http://localhost:5000/books/1